### ISSUE TITLE
Automation 🦠

### ISSUE THREAD

**Issue by portellaa** [ydataai/dockerfiles#4]
The repo is already split in folders each one for each image, although it isn't yet automated, ideally they should be connected.

https://skaffold.dev/ this could be interesting as bootstrap

List of things to automate
- [x] build of images extracting all the information from the folder for the image, or something like that
- [x] versioning, for each image of for all, need investigation
- [x] deployment to docker hub

**Comment by portellaa** [comment]
@rafaelcpalmeida can we close this issue?

**Comment by rafaelcpalmeida** [comment]
Closed by #36.
