### ISSUE TITLE
fix: can't access GPUs from certain bundles

### ISSUE THREAD

**Issue by portellaa** [ydataai/dockerfiles#69]
**Environment:** both

## Actual Behaviour
Currently when trying to list the GPUs available or use them, it doesn't detects a GPU.
This happens in the bundle none and ydata, in the none i tried to install the tensorflow through pip and it failed.

## Expected behaviour
When using `tf.config.experimental.list_physical_devices('GPU')` it should list one GPU

## Steps To Reproduce
1. create a jupyterlab using the bundle none or ydata
2. open the lab, install tensorflow > 2.2 and < 2.3 (don't install 2.4, it requires cuda 11) if necessary (in the bundle none)
3. run `tf.config.experimental.list_physical_devices('GPU')`

**Comment by rafaelcpalmeida** [comment]
Couldn't reproduce this. YData bundle is working with Tensorflow 2.2. Installed Tensorflow 2.2 on a "plain" JupyterLab image and it's working.
