### ISSUE TITLE
TensorFlow 2.1 and 2.2 images gives error when importing ydata lib

### ISSUE THREAD

**Issue by gmartinsribeiro** [ydataai/dockerfiles#9]
How to reproduce:
import ydata.synthesizers

Error:
ModuleNotFoundError: No module named 'torch'

Fix:
ydata lib needs to be installed along with its requirements.txt
- TensorFlow 2.1
- TensorFlow 2.2

-> Good first task for André?

**Comment by portellaa** [comment]
this will be a different image within the new bundles and is already addressed
